Impoting Libraries

In [1]:
import json
import hashlib
import datetime
from breeze_connect import BreezeConnect
import urllib
import pandas as pd
import numpy as np
import pprint

Key and Secrets

In [2]:
Key = '7!H%76ws4g803362Q58473W452b24675'
Secret = '59124Z94T00918XCp143O2l4w0L37g~3'

# Obtain your session key from https://api.icicidirect.com/apiuser/login?api_key=YOUR_API_KEY
# Incase your api-key has special characters(like +,=,!) then encode the api key before using in the url as shown below.
link = f'https://api.icicidirect.com/apiuser/login?api_key={urllib.parse.quote_plus(Key)}'
link

'https://api.icicidirect.com/apiuser/login?api_key=7%21H%2576ws4g803362Q58473W452b24675'

In [3]:
api_session = '28936774' #enter api session from link

In [4]:
# Initialize SDK
breeze = BreezeConnect(api_key=Key)

# Generate Session
breeze.generate_session(api_secret=Secret,
                        session_token=api_session)

In [5]:

# Generate ISO8601 Date/DateTime String
current_time = datetime.datetime.now()

def get_date_str(date):
    '''This take datetime object and convert into iso String req by ICICI Breeze'''
    current_date_str = date.strftime("%d/%m/%Y")
    iso_date_string = datetime.datetime.now().strptime(current_date_str,"%d/%m/%Y").isoformat()[:10] + 'T05:30:00.000Z'
    return iso_date_string
    
def get_date_time_str(date):
    '''This take datetime object and convert into iso String req by ICICI Breeze'''
    current_date_time_str = date.strftime("%d/%m/%Y %H:%M:%S")
    iso_date_time_string = datetime.datetime.strptime(current_date_time_str,"%d/%m/%Y %H:%M:%S").isoformat()[:19] + '.000Z'
    return iso_date_time_string

In [6]:
#get customer details

breeze.get_customer_details(api_session=api_session)

{'Success': {'exg_trade_date': {'NSE': '15-Dec-2023',
   'BSE': '15-Dec-2023',
   'FNO': '15-Dec-2023',
   'NDX': '15-Dec-2023'},
  'exg_status': {'NSE': 'O', 'BSE': 'O', 'FNO': 'Y', 'NDX': 'O'},
  'segments_allowed': {'Trading': 'Y',
   'Equity': 'Y',
   'Derivatives': 'D',
   'Currency': 'D'},
  'idirect_userid': 'AG911462',
  'idirect_user_name': 'ANKIT',
  'idirect_ORD_TYP': '',
  'idirect_lastlogin_time': '15-Dec-2023 14:26:04',
  'mf_holding_mode_popup_flg': 'N',
  'commodity_exchange_status': 'N',
  'commodity_trade_date': '15-Dec-2023',
  'commodity_allowed': 'O'},
 'Status': 200,
 'Error': None}

Get holdings details

In [7]:
#get holdings
breeze.get_demat_holdings()

{'Success': [{'stock_code': 'SOUBAN',
   'stock_ISIN': 'INE683A01023',
   'quantity': '10',
   'demat_total_bulk_quantity': '10',
   'demat_avail_quantity': '0',
   'blocked_quantity': '0',
   'demat_allocated_quantity': '10'}],
 'Status': 200,
 'Error': None}

In [26]:
#get_stock details 
current_time = datetime.datetime.now()
hours = 10
qty = 10
interval = '5minute'
exchange = 'NSE'
stock_code = 'ITC'
start_time = get_date_time_str(current_time-datetime.timedelta(hours=8))
end_time = get_date_time_str(current_time)

def get_historical_data():
    ICIBAN = breeze.get_historical_data(interval=interval,
                                from_date= start_time,
                                to_date= end_time,
                                stock_code=stock_code,
                                exchange_code=exchange,
                                product_type="cash")
    print(f'Data got from server {ICIBAN}')
    if ICIBAN['Status']==200:
            data = ICIBAN['Success']
            data = pd.DataFrame(data)      
    else:
            data = str(f'there was an error in getting the data Error: {ICIBAN["Status"]}. Source {ICIBAN}')

    return data

In [27]:

data = get_historical_data()

if type(data) != 'str':
    data = data[['datetime','stock_code', 'close','volume']]

data

Data got from server {'Success': [{'datetime': '2023-12-14 15:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '458.3', 'high': '458.3', 'low': '458.3', 'close': '458.3', 'volume': '-1787', 'open_interest': None, 'count': 0}, {'datetime': '2023-12-15 09:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.35', 'high': '460.45', 'low': '459.3', 'close': '460.3', 'volume': '169483', 'open_interest': None, 'count': 1}, {'datetime': '2023-12-15 09:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '461.9', 'high': '461.9', 'low': '461.9', 'close': '461.9', 'volume': '0', 'open_interest': None, 'count': 2}, {'datetime': '2023-12-15 09:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '461.9', 'high': '461.9', 'low': '460.3', 'close': '460.3', 'volume': '89235', 'open_interest': None, 'count': 3}, {'datetime': '2023-12-15 09:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '460.45', 'high': '462.85', 'low': '460.45', 'close': '462.15', 'volume': '322562', 'open_interest': None, 'count': 4}, {'datetime': '2023-12-15 09:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '462.25', 'high': '462.8', 'low': '461.6', 'close': '461.85', 'volume': '153608', 'open_interest': None, 'count': 5}, {'datetime': '2023-12-15 09:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '461.8', 'high': '462.6', 'low': '461', 'close': '462.1', 'volume': '288651', 'open_interest': None, 'count': 6}, {'datetime': '2023-12-15 09:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '462.35', 'high': '462.6', 'low': '461.6', 'close': '461.65', 'volume': '249100', 'open_interest': None, 'count': 7}, {'datetime': '2023-12-15 09:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '461.45', 'high': '461.65', 'low': '460.15', 'close': '460.2', 'volume': '205303', 'open_interest': None, 'count': 8}, {'datetime': '2023-12-15 09:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '460.2', 'high': '460.25', 'low': '459', 'close': '460.2', 'volume': '228330', 'open_interest': None, 'count': 9}, {'datetime': '2023-12-15 09:50:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '460.35', 'high': '460.5', 'low': '458.75', 'close': '458.85', 'volume': '152503', 'open_interest': None, 'count': 10}, {'datetime': '2023-12-15 09:55:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '458.8', 'high': '459.5', 'low': '458.65', 'close': '459', 'volume': '104685', 'open_interest': None, 'count': 11}, {'datetime': '2023-12-15 10:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '460.05', 'high': '460.3', 'low': '456.85', 'close': '457.45', 'volume': '1866611', 'open_interest': None, 'count': 12}, {'datetime': '2023-12-15 10:05:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.9', 'high': '460.1', 'low': '459.4', 'close': '459.65', 'volume': '125797', 'open_interest': None, 'count': 13}, {'datetime': '2023-12-15 10:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.55', 'high': '460.4', 'low': '459.5', 'close': '459.85', 'volume': '142400', 'open_interest': None, 'count': 14}, {'datetime': '2023-12-15 10:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.85', 'high': '459.95', 'low': '459.2', 'close': '459.25', 'volume': '117840', 'open_interest': None, 'count': 15}, {'datetime': '2023-12-15 10:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.3', 'high': '459.75', 'low': '458.85', 'close': '458.95', 'volume': '149590', 'open_interest': None, 'count': 16}, {'datetime': '2023-12-15 10:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '459.05', 'high': '459.3', 'low': '458.1', 'close': '458.4', 'volume': '211771', 'open_interest': None, 'count': 17}, {'datetime': '2023-12-15 10:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '458.45', 'high': '458.7', 'low': '458.35', 'close': '458.5', 'volume': '156975', 'open_interest': None, 'count': 18}, {'datetime': '2023-12-15 10:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '458.4', 'high': '458.75', 'low': '457.3', 'close': '457.45', 'volume': '188797', 'open_interest': None, 'count': 19}, {'datetime': '2023-12-15 10:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.45', 'high': '457.5', 'low': '456.7', 'close': '456.95', 'volume': '207490', 'open_interest': None, 'count': 20}, {'datetime': '2023-12-15 10:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.05', 'high': '457.2', 'low': '456.75', 'close': '456.95', 'volume': '123147', 'open_interest': None, 'count': 21}, {'datetime': '2023-12-15 10:50:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.9', 'high': '456.95', 'low': '456.65', 'close': '456.65', 'volume': '122162', 'open_interest': None, 'count': 22}, {'datetime': '2023-12-15 10:55:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.6', 'high': '457.5', 'low': '456.6', 'close': '456.85', 'volume': '178390', 'open_interest': None, 'count': 23}, {'datetime': '2023-12-15 11:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.45', 'high': '457.5', 'low': '456.6', 'close': '456.85', 'volume': '1138661', 'open_interest': None, 'count': 24}, {'datetime': '2023-12-15 11:05:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.35', 'high': '457.5', 'low': '456.8', 'close': '457.05', 'volume': '142210', 'open_interest': None, 'count': 25}, {'datetime': '2023-12-15 11:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.15', 'high': '457.15', 'low': '456.6', 'close': '456.8', 'volume': '93970', 'open_interest': None, 'count': 26}, {'datetime': '2023-12-15 11:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.75', 'high': '457', 'low': '456.5', 'close': '456.8', 'volume': '88460', 'open_interest': None, 'count': 27}, {'datetime': '2023-12-15 11:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.65', 'high': '456.75', 'low': '456.5', 'close': '456.6', 'volume': '85365', 'open_interest': None, 'count': 28}, {'datetime': '2023-12-15 11:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.55', 'high': '456.8', 'low': '456.55', 'close': '456.65', 'volume': '87551', 'open_interest': None, 'count': 29}, {'datetime': '2023-12-15 11:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.65', 'high': '456.75', 'low': '456.6', 'close': '456.65', 'volume': '69347', 'open_interest': None, 'count': 30}, {'datetime': '2023-12-15 11:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.75', 'high': '456.75', 'low': '456.5', 'close': '456.65', 'volume': '73934', 'open_interest': None, 'count': 31}, {'datetime': '2023-12-15 11:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.65', 'high': '457', 'low': '456.6', 'close': '456.95', 'volume': '100573', 'open_interest': None, 'count': 32}, {'datetime': '2023-12-15 11:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457', 'high': '457.25', 'low': '456.85', 'close': '457.2', 'volume': '78545', 'open_interest': None, 'count': 33}, {'datetime': '2023-12-15 11:50:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457.25', 'high': '457.25', 'low': '456.9', 'close': '457.05', 'volume': '94366', 'open_interest': None, 'count': 34}, {'datetime': '2023-12-15 11:55:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '457', 'high': '457.25', 'low': '456.85', 'close': '456.85', 'volume': '101783', 'open_interest': None, 'count': 35}, {'datetime': '2023-12-15 12:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.9', 'high': '456.9', 'low': '455.25', 'close': '455.45', 'volume': '1522091', 'open_interest': None, 'count': 36}, {'datetime': '2023-12-15 12:05:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.75', 'high': '456.9', 'low': '456.5', 'close': '456.55', 'volume': '84337', 'open_interest': None, 'count': 37}, {'datetime': '2023-12-15 12:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.6', 'high': '456.8', 'low': '456.5', 'close': '456.65', 'volume': '89500', 'open_interest': None, 'count': 38}, {'datetime': '2023-12-15 12:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.6', 'high': '456.7', 'low': '456.35', 'close': '456.4', 'volume': '112984', 'open_interest': None, 'count': 39}, {'datetime': '2023-12-15 12:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.45', 'high': '456.95', 'low': '456.1', 'close': '456.9', 'volume': '168397', 'open_interest': None, 'count': 40}, {'datetime': '2023-12-15 12:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.9', 'high': '457.15', 'low': '456.7', 'close': '456.8', 'volume': '81846', 'open_interest': None, 'count': 41}, {'datetime': '2023-12-15 12:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.75', 'high': '456.95', 'low': '456.5', 'close': '456.55', 'volume': '85448', 'open_interest': None, 'count': 42}, {'datetime': '2023-12-15 12:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.5', 'high': '456.6', 'low': '456.25', 'close': '456.25', 'volume': '65755', 'open_interest': None, 'count': 43}, {'datetime': '2023-12-15 12:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.3', 'high': '456.5', 'low': '455.85', 'close': '456', 'volume': '168099', 'open_interest': None, 'count': 44}, {'datetime': '2023-12-15 12:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.9', 'high': '456', 'low': '455.35', 'close': '455.45', 'volume': '285563', 'open_interest': None, 'count': 45}, {'datetime': '2023-12-15 12:50:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.5', 'high': '455.55', 'low': '455.35', 'close': '455.45', 'volume': '127874', 'open_interest': None, 'count': 46}, {'datetime': '2023-12-15 12:55:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.5', 'high': '455.5', 'low': '455.25', 'close': '455.4', 'volume': '102378', 'open_interest': None, 'count': 47}, {'datetime': '2023-12-15 13:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.4', 'high': '456.15', 'low': '455.35', 'close': '455.75', 'volume': '1831385', 'open_interest': None, 'count': 48}, {'datetime': '2023-12-15 13:05:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.5', 'high': '455.5', 'low': '455.3', 'close': '455.3', 'volume': '121129', 'open_interest': None, 'count': 49}, {'datetime': '2023-12-15 13:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.3', 'high': '455.4', 'low': '455', 'close': '455.1', 'volume': '133065', 'open_interest': None, 'count': 50}, {'datetime': '2023-12-15 13:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.05', 'high': '455.3', 'low': '455', 'close': '455.25', 'volume': '115896', 'open_interest': None, 'count': 51}, {'datetime': '2023-12-15 13:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.3', 'high': '455.5', 'low': '455.25', 'close': '455.5', 'volume': '144055', 'open_interest': None, 'count': 52}, {'datetime': '2023-12-15 13:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.35', 'high': '455.5', 'low': '455.2', 'close': '455.3', 'volume': '105988', 'open_interest': None, 'count': 53}, {'datetime': '2023-12-15 13:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.3', 'high': '455.5', 'low': '455.1', 'close': '455.5', 'volume': '101676', 'open_interest': None, 'count': 54}, {'datetime': '2023-12-15 13:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.45', 'high': '456.3', 'low': '455.35', 'close': '456', 'volume': '143388', 'open_interest': None, 'count': 55}, {'datetime': '2023-12-15 13:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456', 'high': '456.1', 'low': '455.65', 'close': '455.9', 'volume': '124672', 'open_interest': None, 'count': 56}, {'datetime': '2023-12-15 13:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.9', 'high': '456.7', 'low': '455.65', 'close': '456.6', 'volume': '167449', 'open_interest': None, 'count': 57}, {'datetime': '2023-12-15 13:50:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.55', 'high': '456.8', 'low': '455.7', 'close': '455.85', 'volume': '218761', 'open_interest': None, 'count': 58}, {'datetime': '2023-12-15 13:55:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.75', 'high': '456.25', 'low': '455.65', 'close': '456', 'volume': '269091', 'open_interest': None, 'count': 59}, {'datetime': '2023-12-15 14:00:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.95', 'high': '457.1', 'low': '455.7', 'close': '457', 'volume': '2041717', 'open_interest': None, 'count': 60}, {'datetime': '2023-12-15 14:05:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.75', 'high': '455.85', 'low': '455.5', 'close': '455.6', 'volume': '162708', 'open_interest': None, 'count': 61}, {'datetime': '2023-12-15 14:10:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.6', 'high': '456', 'low': '455.5', 'close': '455.9', 'volume': '173522', 'open_interest': None, 'count': 62}, {'datetime': '2023-12-15 14:15:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '455.85', 'high': '456.45', 'low': '455.8', 'close': '456.45', 'volume': '143554', 'open_interest': None, 'count': 63}, {'datetime': '2023-12-15 14:20:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.15', 'high': '456.35', 'low': '455.9', 'close': '456.2', 'volume': '140779', 'open_interest': None, 'count': 64}, {'datetime': '2023-12-15 14:25:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.1', 'high': '456.4', 'low': '455.7', 'close': '456.35', 'volume': '142221', 'open_interest': None, 'count': 65}, {'datetime': '2023-12-15 14:30:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.35', 'high': '456.4', 'low': '456.05', 'close': '456.15', 'volume': '125985', 'open_interest': None, 'count': 66}, {'datetime': '2023-12-15 14:35:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456.35', 'high': '456.35', 'low': '455.9', 'close': '456', 'volume': '115573', 'open_interest': None, 'count': 67}, {'datetime': '2023-12-15 14:40:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open': '456', 'high': '456.35', 'low': '455.95', 'close': '456.15', 'volume': '152087', 'open_interest': None, 'count': 68}, {'datetime': '2023-12-15 14:45:00', 'stock_code': 'ITC', 'exchange_code': 'NSE', 'product_type': None, 'expiry_date': None, 'right': None, 'strike_price': None, 'open'

               datetime stock_code   close  volume
0   2023-12-14 15:00:00        ITC   458.3   -1787
1   2023-12-15 09:00:00        ITC   460.3  169483
2   2023-12-15 09:10:00        ITC   461.9       0
3   2023-12-15 09:15:00        ITC   460.3   89235
4   2023-12-15 09:20:00        ITC  462.15  322562
..                  ...        ...     ...     ...
70  2023-12-15 14:50:00        ITC   455.8  141765
71  2023-12-15 14:55:00        ITC  456.65  263049
72  2023-12-15 15:00:00        ITC   458.1  275044
73  2023-12-15 15:05:00        ITC  457.45  896192
74  2023-12-15 15:10:00        ITC   457.7  204736

[75 rows x 4 columns]

In [28]:
signal()

ShortEMA of -2 456.73
datetime      2023-12-15 15:10:00
stock_code                    ITC
close                       457.7
volume                     204736
shortEMA                   456.92
longEMA                    456.52
Name: 74, dtype: object
************Singal Recieved 1*************

1

In [29]:
data

               datetime stock_code   close  volume  shortEMA  longEMA
0   2023-12-14 15:00:00        ITC   458.3   -1787    458.30   458.30
1   2023-12-15 09:00:00        ITC   460.3  169483    458.70   458.48
2   2023-12-15 09:10:00        ITC   461.9       0    459.34   458.79
3   2023-12-15 09:15:00        ITC   460.3   89235    459.53   458.93
4   2023-12-15 09:20:00        ITC  462.15  322562    460.06   459.22
..                  ...        ...     ...     ...       ...      ...
70  2023-12-15 14:50:00        ITC   455.8  141765    456.04   456.06
71  2023-12-15 14:55:00        ITC  456.65  263049    456.16   456.12
72  2023-12-15 15:00:00        ITC   458.1  275044    456.55   456.30
73  2023-12-15 15:05:00        ITC  457.45  896192    456.73   456.40
74  2023-12-15 15:10:00        ITC   457.7  204736    456.92   456.52

[75 rows x 6 columns]

In [24]:
def signal():
    data['shortEMA'] = data.close.ewm(span=9, adjust=False).mean().round(2)
    data['longEMA'] = data.close.ewm(span=21, adjust=False).mean().round(2)

    print(f"ShortEMA of -2 {data['shortEMA'].iloc[-2]}")
    print(data.iloc[-1])

# Determine the crossover point
    if data['shortEMA'].iloc[-1] > data['longEMA'].iloc[-1] and data['shortEMA'].iloc[-2] > data['longEMA'].iloc[-2]:
        print(f'************Singal Recieved 1*************')
        return 1

    elif data['shortEMA'].iloc[-1] < data['longEMA'].iloc[-1]: #and shortEMA[-3] > longEMA[-3]:
        return 0

In [37]:
def buy(price):
    breeze.place_order(stock_code=stock_code,
                    exchange_code=exchange,
                    product="cash",
                    action="buy",
                    order_type="limit",
                    stoploss="",
                    quantity=qty,
                    price=price,
                    validity="day"
                )

def sell(price):
    breeze.place_order(stock_code=stock_code,
                    exchange_code=exchange,
                    product="cash",
                    action="sell",
                    order_type="limit",
                    stoploss="",
                    quantity=qty,
                    price=price,
                    validity="day"
                )

               datetime stock_code   close  volume  shortEMA  longEMA
0   2023-12-13 15:00:00        ITC   455.6   -9656    455.60   455.60
1   2023-12-14 09:00:00        ITC  458.05  106060    456.09   455.82
2   2023-12-14 09:10:00        ITC     460       0    456.87   456.20
3   2023-12-14 09:15:00        ITC  456.25  229829    456.75   456.21
4   2023-12-14 09:20:00        ITC   456.5  420156    456.70   456.23
..                  ...        ...     ...     ...       ...      ...
78  2023-12-14 15:30:00        ITC   460.1  641572    460.26   460.07
79  2023-12-14 15:40:00        ITC   460.1     732    460.23   460.08
80  2023-12-14 15:45:00        ITC   460.1     284    460.20   460.08
81  2023-12-14 15:50:00        ITC   460.1    5187    460.18   460.08
82  2023-12-14 15:55:00        ITC   460.1    1846    460.17   460.08

[83 rows x 6 columns]

In [40]:
breeze.ws_connect()
position = 0
buy_price = 0
sell_price = 0
# Callback to receive ticks.
def on_ticks(ticks):
    #data.loc[len(data.index)] = [ticks]      #update the data 

    price = ticks
    time = ticks
    
    if not position and signal():
        buy_price = price
        #print(f'**************GOING LONG AT A PRICE {buy_price}e AT {time}')
        #buy(price)
    elif position and not signal():
        sell_price = price
        #print(f'*********CLOSING LONG POSITION AT A PRICE {sell_price} WITH PROFIT OF {buy_price-sell_price}********')
    #print("Ticks: {}".format(ticks))
    keys = ticks.keys()
    print(keys)
# Assign the callbacks.
breeze.on_ticks = on_ticks


# subscribe to Real Time Streaming OHLCV Data of stocks
breeze.subscribe_feeds(exchange_code=exchange, stock_code=stock_code, product_type='cash', interval="1second", get_exchange_quotes=False, get_market_depth=True)



# ws_disconnect (it will disconnect from all actively connected servers)

{'message': 'Stock ITC subscribed successfully'}

In [38]:
breeze.ws_disconnect()

ShortEMA of -2 456.73
datetime      2023-12-15 15:10:00
stock_code                    ITC
close                       457.7
volume                     204736
shortEMA                   456.92
longEMA                    456.52
Name: 74, dtype: object
************Singal Recieved 1*************
dict_keys(['interval', 'exchange_code', 'stock_code', 'low', 'high', 'open', 'close', 'volume', 'datetime'])

[{'message': 'socket server for rate refresh  has been disconnected.'},
 {'message': 'socket server for OHLCV Streaming has been disconnected.'},
 {'message': 'socket server is not connected to order refresh.'}]

In [ ]:
old = 'interval', 'exchange_code', 'stock_code', 'low', 'high', 'open', 'close', 'volume', 'datetime'